FROM ubuntu

ENV PYTHON3_VERSION 3.10
ENV PYTHON2_VERSION 2.7
ENV PYTHONPATH /usr/bin/python2:/usr/bin/python3
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV HADOOP_VERSION 3.3.4
ENV HADOOP_MINOR_VERSION 3.3
ENV HADOOP_HOME /usr/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR $HADOOP_HOME/etc/hadoop
ENV HDFS_NAMENODE_USER root
ENV HDFS_SECONDARYNAMENODE_USER hadoop
ENV HDFS_DATANODE_USER root
ENV HDFS_SECONDARYDATANODE_USER hadoop

COPY hadoop-3.3.4.tar.gz /
# RUN sh /apache-ecosystem-setup.sh

# Install java, python and other required components
RUN apt-get update \
    && apt-get install -y wget ssh pdsh openssh-server curl default-jre default-jdk python2 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON3_VERSION} 1 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON2_VERSION} 2

# Create group and users
RUN groupadd hadoop \
    && useradd -m -u 1500 -g sudo -G hadoop hadoop-service-admin

# Install hadoop
# RUN wget https://dlcdn.apache.org/hadoop/common/stable/hadoop-${HADOOP_VERSION}.tar.gz \
RUN tar zvxf hadoop-${HADOOP_VERSION}.tar.gz -C /usr/ \
    && chown -R hadoop-service-admin:hadoop ${HADOOP_HOME} \
    && mkdir $HADOOP_HOME/conf \
    && echo $(uname -n) > $HADOOP_HOME/conf/masters \
    && echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/environment

# Keys dos nodes. Necessarias para se comunicarem por SSH
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa \
    && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys \
    && chmod 600 ~/.ssh/authorized_keys

COPY config /root/.ssh

RUN chmod 600 /root/.ssh/config

ENTRYPOINT [ "tail", "-f", "/dev/null"]