FROM ubuntu

ENV PYTHON3_VERSION 3.10
ENV PYTHON2_VERSION 2.7
ENV JAVA_VERSION 1.8.0
ENV PYTHONPATH /usr/bin/python2:/usr/bin/python3
ENV JAVA_HOME /usr/lib/jvm/java-$JAVA_VERSION-openjdk-amd64
ENV HADOOP_VERSION 3.3.4
ENV HADOOP_MINOR_VERSION 3.3
ENV HADOOP_HOME /usr/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR $HADOOP_HOME/etc/hadoop
ENV HDFS_NAMENODE_USER root
ENV HDFS_SECONDARYNAMENODE_USER root
ENV HDFS_DATANODE_USER root
ENV HDFS_SECONDARYDATANODE_USER root

COPY hadoop-3.3.4.tar.gz /
COPY bootstrap.sh /

RUN apt-get update \
    && apt-get install -y wget ssh openssh-server openjdk-8-jdk curl python2 vim \
    && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON3_VERSION} 1 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON2_VERSION} 2 \
#   hadoop
#   && wget https://dlcdn.apache.org/hadoop/common/stable/hadoop-${HADOOP_VERSION}.tar.gz \
    && tar zvxf hadoop-3.3.4.tar.gz -C /usr/ \
    && echo "export JAVA_HOME=${JAVA_HOME}" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh \
    && chown -R root:root ${HADOOP_HOME}

# Create group ,users and add know hosts
RUN groupadd hadoop \
    && useradd -m -u 1500 -g sudo -G hadoop hadoop-service-admin \
    && ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa \
    && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys \
    && chmod 600 ~/.ssh/authorized_keys

COPY core-site.xml $HADOOP_HOME/etc/hadoop/
COPY hdfs-site.xml $HADOOP_HOME/etc/hadoop/

ENTRYPOINT [ "sh", "/bootstrap.sh"]