version: "1.0"
services:
  name-node:
    image: phdev1/hadoop-base-node:1.0.0
    container_name: name-node
    hostname: hp-nmnd01
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8088:8088"
    networks: 
      hadoop-network:
        ipv4_address: 10.5.0.2
    environment:
      - "SPARK_LOCAL_IP=hp-nmnd01"
  mysql-database:
    image: mysql
    container_name: mysql-database
    hostname: db-mysql01
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks: 
      hadoop-network:
        ipv4_address: 10.5.0.5
networks:
  hadoop-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16